### ISSUE TITLE
Module is crashing on pristine 2.1.3

### ISSUE THREAD

**Issue by doekia** [thelia-modules/CustomerGroup#3]
Actually the module is missing the Config/customer-group.xml
The installation is then partial and cause Customer page to fail.

If a Config/customer-group.cml is present, the module failt to install with invalid DTD message during xml parsing

**Comment by bcbrr** [comment]
Could you give more details ?
I can install and activate the module on a pristine Thelia 2.1.3 (PHP 5.5.9).

The module CustomerGroup itself does not have a `Config/customer-group.xml` file since this file is meant for other modules to define customer groups, and we don't define any default groups.

**Comment by doekia** [comment]
Althrough I don't think it is related to the issue I running php 5.4.40.

When installing the module the first time w/o any records in customer_group:
- accessing the customer tab raise: Call to a member function getId() on a non-object for CustomerGroup/EventListener/CustomerCustomerGroup.php on line 61
- creating a new account from the Front raise an almost similiar error (sorry I lost track of it right now since I manually populated my tables)

Finaly, when I put the customer-group.xml, each time I try to activate the module I face this json response:

```
[ERROR 94] Validation failed: no DTD found ! (in n/a - line 1, column 22)
[ERROR 76] Opening and ending tag mismatch: description line 5 and descriptive (in n/a - line 6, column 32)
[ERROR 76] Opening and ending tag mismatch: description line 9 and descriptive (in n/a - line 10, column 32)
[ERROR 76] Opening and ending tag mismatch: description line 9 and customergroup (in n/a - line 11, column 21)
[ERROR 76] Opening and ending tag mismatch: description line 16 and descriptive (in n/a - line 17, column 32)
[ERROR 76] Opening and ending tag mismatch: description line 20 and descriptive (in n/a - line 21, column 32)
[ERROR 76] Opening and ending tag mismatch: description line 20 and customergroup (in n/a - line 22, column 21)
[ERROR 76] Opening and ending tag mismatch: descriptive line 18 and customergroups (in n/a - line 25, column 18)
[ERROR 77] Premature end of data in tag description line 16 (in n/a - line 26, column 1)
[ERROR 77] Premature end of data in tag descriptive line 14 (in n/a - line 26, column 1)
[ERROR 77] Premature end of data in tag customergroup line 13 (in n/a - line 26, column 1)
[ERROR 77] Premature end of data in tag descriptive line 7 (in n/a - line 26, column 1)
[ERROR 77] Premature end of data in tag description line 5 (in n/a - line 26, column 1)
[ERROR 77] Premature end of data in tag descriptive line 3 (in n/a - line 26, column 1)
[ERROR 77] Premature end of data in tag customergroup line 2 (in n/a - line 26, column 1)
[ERROR 77] Premature end of data in tag customergroups line 1 (in n/a - line 26, column 1)
```

The xml the one from the README.md:

```
<customergroups xmlns="urn:thelia:module:customer-group">
    <customergroup code="customer">
        <descriptive locale="en_US">
            <title>Customer</title>
            <description>Basic customer<description>
        </descriptive>
        <descriptive locale="fr_FR">
            <title>Client</title>
            <description>Client de base<description>
        </descriptive>
    </customergroup>

    <customergroup code="vip">
        <descriptive locale="en_US">
            <title>VIP</title>
            <description>VIP customer !<description>
        </descriptive>
        <descriptive locale="fr_FR">
            <title>VIP</title>
            <description>Client VIP !<description>
        </descriptive>
    </customergroup>

    <default>customer</default>
</customergroups>
```

May well be related to some xml libraries I have on my system even do I am clueless about which and why ... just stable debian7 nothing fancy here.

**Comment by bcbrr** [comment]
Sorry for the delay, this was fixed as far as I can tell (https://github.com/thelia-modules/CustomerGroup/pull/7).
